version: "3.9"
services:

  oauth2-proxy:
    build: ./oauth2_proxy
    restart: always
    ports: 
      - 4180:4180
    volumes:
      - ./oauth2_proxy/config.template.yaml:/app/config.template.yaml
    environment:
      - ISSUER_URL=${ISSUER_URL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DATASPACE_URL=${DATASPACE_URL}
    command: |
      oauth2-proxy 
        --alpha-config=/tmp/config.yaml 
        --cookie-secret=${COOKIE_SECRET} 
        --email-domain="*" 
        --skip-provider-button
        --cookie-secure=false
        --cookie-refresh=3m
        --skip-jwt-bearer-tokens=true
        --cookie-samesite=lax
        --cookie-expire=12h
        --skip-auth-route="/api/ws/plugins/telemetry"
        
  frontend:
    build: ./frontend
    restart: always
    environment:
      - WDS_SOCKET_PORT=4180
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend/index.js:/app/index.js